name: prod_push

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/laravel/prod
          eval `ssh-agent`
          ssh-add /var/www/el
          git checkout prod
          git fetch origin prod
          git reset --hard origin/prod
          chmod +x /var/www/laravel/prod/scripts/deploy.sh
          ./scripts/deploy.sh
